# Generated by Django 2.0.9 on 2018-12-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oda', '0003_brand_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='manager',
        ),
    ]
